== Contribution Guidelines

Slack Spring Boot Starter is released under the https://github.com/hndrs/slack-spring-boot-starter/blob/main/LICENSE[MIT license].
These guidelines are here to help you getting started contributing to this project.

=== Code of Conduct

Please read and follow our https://github.com/hndrs/.github/blob/main/CODE_OF_CONDUCT.md[Code of Conduct^] before contributing to the project.
By contributing we expect you to follow the this code of conduct and furthermore advise you to report any misbehaviour you encounter to the maintainers.

=== Contact

Feel free to to ope]

=== Missing Feature

If you are missing a feature, you can create an issue, stating which feature is missing and please reference the according https://api.slack.com/[Slack Api Documentation^] entry.

=== Contributing

If you want to contribute to the project, please create or pick the according issue, fork the project and submit a pull request.

==== Scope

To add a new Feature or Slack Api Method:

* create the abstract class for the Method
* extend the according https://github.com/kreait/slack-spring-boot-starter/tree/master/client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group[Method Group]
* create a https://github.com/kreait/slack-spring-boot-starter/tree/master/client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring[Default Implementation] and extend the https://github.com/kreait/slack-spring-boot-starter/blob/master/client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/DefaultSlackClient.kt[DefaultSlackClient]
* test your implementation in the https://github.com/kreait/slack-spring-boot-starter/tree/master/client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring[Test module] (probably take already existing tests as an example)
* extend the https://github.com/kreait/slack-spring-boot-starter/tree/master/client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test[Test Api Client] and create the https://github.com/kreait/slack-spring-boot-starter/tree/master/client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test[Mock Tests]

==== DTOS

* All data classes should be located in the https://github.com/kreait/slack-spring-boot-starter/tree/master/data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson[slack-jackson-dto package]

* Create a `.sample()` extension for every created dto in the https://github.com/kreait/slack-spring-boot-starter/tree/master/data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson[slack-jackson-dto-test-extension] package, which simply returns a created object with empty values

==== Bugs

Currently, not all methods are tested against a real workspace, but have been implemented according to the slack api documentation, so it could happen that even implemented methods don't work properly.
If you encounter a bug, feel free to raise an issue, or fix it and submit a pull request.

==== Code Conventions

These guidelines will help to improve the process of reviewing contributions.

- We endorse readable and formatted code. The default formatting options provided by IDEs like IntelliJ, Netbeans and Eclipse
are sufficient in most cases. If you are creating non-trivial pull requests please make sure your code is well documented (kdoc).

- This will help us to better read your code and follow your intentions you are trying to achieve.

- We'd also like you to add Unit Tests (JUnit 5).

- Regular rebasing of your branch against the current master would also help a lot (or the target branch you're building upon).

- When writing commit messages please follow the style we used in previous ones (you can take a look at existing pull-requests for that).
