:source-highlighter: prettify

:version: 1.0.0.RC1

= Slack Spring Boot

image:https://travis-ci.com/kreait/slack-spring-boot-starter.svg?branch=master[link="https://travis-ci.com/kreait/slack-spring-boot-starter"]
image:https://sonarcloud.io/api/project_badges/measure?project=com.kreait.slack-spring-boot-starter&metric=alert_status&metric=alert_status[link="https://sonarcloud.io/dashboard?id=com.kreait.slack-spring-boot-starter"]
image:https://img.shields.io/badge/version-{version}-fffff.svg[]
image:https://sonarcloud.io/api/project_badges/measure?project=com.kreait.slack-spring-boot-starter&metric=coverage[link="https://sonarcloud.io/dashboard?id=com.kreait.slack-spring-boot-starter"]
image:https://img.shields.io/discord/523866370778333184.svg[link="https://discord.gg/fXfQmdJ"]
image:http://img.shields.io/badge/stackoverflow-slack-informational.svg[link="https://meta.stackoverflow.com/questions/tagged/slack"]

Find our documentation on https://slack-spring-boot.kreait.dev/


== Create a Spring Boot Application

Create a new spring boot application for example on https://start.spring.io (best to use kotlin and gradle for this example)

Add the following to your *build.gradle* file

[source]
--
repositories { maven { url "https://libs.olaph.io" } }

dependencies {
    implementation(group: "com.kreait.slack", name: "slack-spring-boot-starter", version: "{version}")
 }
--

=== Credentials

Locate your app credentials under the *Basic Information* menu item on https://api.slack.com/apps (select your app) By default there is 3 ways adding your slack credentials to the application

1. Create a file $HOME/.slack/credentials

    slack_app_client_id=<client_id>
    slack_app_client_secret=<client_secret>
    slack_app_signing_secret=<signing secret>


2. Set Environment Variables

    SLACK_APP_CLIENT_ID=<client_id>
    SLACK_APP_CLIENT_SECRET=<client_secret>
    SLACK_APP_SIGNING_SECRET=<signing secret>


3. Set JVM System Properties

    slack.application.client-id=<client_id>
    slack.application.client-secret=<client_secret>
    slack.application.signing=<signing secret>


If you want to provide your own link:starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/credentials/CredentialsProvider.kt[CredentialsProvider] implement the interface and expose it as a Bean/Component

Start your application

[source]
--
./gradlew bootRun
--
== Contributing

To contribute to the project, please read the https://github.com/kreait/slack-spring-boot-starter/blob/master/CONTRIBUTING.adoc[Contribution Guidelines]
