:source-highlighter: prettify

:version: 1.0.0.M2

= Slack Spring Boot

image:https://travis-ci.com/kreait/slack-spring-boot-starter.svg?branch=master[link="https://travis-ci.com/kreait/slack-spring-boot-starter"]
image:https://sonarcloud.io/api/project_badges/measure?project=com.kreait.slack-spring-boot-starter&metric=alert_status&metric=alert_status[link="https://sonarcloud.io/dashboard?id=com.kreait.slack"]
image:https://img.shields.io/badge/version-{version}-fffff.svg[]
image:https://sonarcloud.io/api/project_badges/measure?project=com.kreait.slack-spring-boot-starter&metric=coverage[link="https://sonarcloud.io/dashboard?id=com.kreait.slack"]
image:https://img.shields.io/discord/523866370778333184.svg[link="https://discord.gg/fXfQmdJ"]
image:http://img.shields.io/badge/stackoverflow-slack-informational.svg[link="https://meta.stackoverflow.com/questions/tagged/slack"]

== Why use slack-spring-boot-starter?

- Comes with a handy set of abstractions that make your life *boilerplate free*
- creating slash commands is as easy as implementing a single link:samples/slack-spring-boot-starter-sample/src/main/kotlin/io/olaph/slack/sample/PingCommandReceiver.kt[*interface*]
- reacting on events is as easy as implementing a single link:samples/slack-spring-boot-starter-sample/src/main/kotlin/io/olaph/slack/sample/ChannelRenamedEventReceiver.kt[*interface*]
- reacting on interactive components is as easy as implementing a single link:samples/slack-spring-boot-starter-sample/src/main/kotlin/io/olaph/slack/sample/DialogWorkflow.kt.kt[*interface*]
- app installation workflow just works and takes care of the whole authentication flow
- supports link:https://api.slack.com/docs/verifying-requests-from-slack[signing] out of the box

== Quickstart Guide

This short guide will guide you through a quick setup

=== Create a Slack App

Now you will need to set-up your App on the Slack API page.
Go to https://api.slack.com/apps Under "Your Apps" create a new Slack App, give it a name and select the slack workspace you want to develop with (you can't change this workspace later)

=== Create a Spring Boot Application

Create a new spring boot application for example on https://start.spring.io (best to use kotlin and gradle for this example)

Add the following to your *build.gradle* file

[source]
--
repositories { maven { url "https://libs.olaph.io" } }

dependencies { //we add changing true because we are working with changing milestone versions at the moment implementation(group: "com.kreait.slack", name: "slack-spring-boot-starter", version: "{version}", changing: true) }
--

Add the following properties to the *application.properties* file

[source]
--
//the url the user should be redirected to on a successful installation
slack.installation.success-redirect-url=

//the url the user should be redirected to on a failure during installation
slack.installation.error-redirect-url=
--

==== Credentials

Locate your app credentials under the *Basic Information* menu item on https://api.slack.com/apps (select your app) By default there is 3 ways adding your slack credentials to the application

1. Create a file $HOME/.slack/credentials

[source]
--
slack_app_client_id=<client_id> slack_app_client_secret=<client_secret> slack_app_signing_secret=<signing secret>
--

2. Set Environment Variables

[source]
--
SLACK_APP_CLIENT_ID=<client_id> SLACK_APP_CLIENT_SECRET=<client_secret> SLACK_APP_SIGNING_SECRET=<signing secret>
--

3. Set JVM System Properties

[source]
--
slack.application.client-id=<client_id> slack.application.client-secret=<client_secret> slack.application.signing=<signing secret>
--

If you want to provide your own link:starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/credentials/CredentialsProvider.kt[CredentialsProvider] implement the interface and expose it as a Bean/Component

Start your application

[source]
--
./gradlew bootRun
--

=== Configuration of your Slack App

Now you will need to set-up your App on the Slack API page.
At this point you might need to use a service like *ngrok* (which we recommend) or any other tunneling software in order to enable forwarding to your local environment.

[source]
--
./ngrok http 8080
--

==== Interactive Components

Head over to the Interactive Components, activate that feature and enter the url with the endpoint ```{ngrok_host}/interactive-components``` this endpoint has automatically been registered with the starter package

==== Slash Commands

Go to Slash Commands and create a new command and point it to the endpoint ```{ngrok_host}/commands``` this endpoint has automatically been registered with the starter package

==== Events Subscription

Go to Event Subscription and point it to the endpoint ```{ngrok_host}/events``` this endpoint has automatically been registred with the starter package

[NOTE]
====
Slack does not allow http access here, so you need https tunneling
====

==== Installing the app

For your app to work it needs to be installed.
For this head over to https://api.slack.com/apps your app and *OAuth & Permissions* and add a redirect url ```{ngrok_host}/installation``` this endpoint has automatically been registered with the starter package Now head to the *Manage Distribution* setting on your app and click the *Add to Slack* button, this will install the app on your application

[NOTE]
====
The Team will be saved in the link:starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/store/TeamStore.kt[*TeamStore*], the starter provides an InMemoryTeamStore which will be reset after you restart the application to persist the installation you have to provide your own implementation with a backing database
====

==== SL4JLoggingReceiver

The starter package will automatically register a custom link:starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/receiver/SL4JLoggingReceiver.kt[receiver] that logs information on incoming events,commands and interactive-components

[NOTE]
====
This receiver is meant to be used for development only to disable it add ```slack.logging.enabled=false``` to your application.properties
====

=== Writing your first CommandReceiver

To write your first command receiver you write a component that implements the link:starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/receiver/SlashCommandReceiver.kt[SlashCommandReceiver] interface you can use the  link:client/slack-api-client/src/main/kotlin/io/olaph/slack/client/SlackClient.kt[SlackClient] that is automatically registered with the starter

Example Ping Receiver that answers with a pong

[source,kotlin]
--
@Component class PingCommandReceiver @Autowired constructor(private val slackClient:
SlackClient) :
SlashCommandReceiver {

    override fun supportsCommand(slackCommand: SlackCommand): Boolean {
        return slackCommand.command.startsWith("/ping")
    }

    override fun onReceiveSlashCommand(slackCommand: SlackCommand, headers: HttpHeaders, team: Team) {
        this.slackClient.chat().postMessage(team.bot.accessToken)
                .with(SlackPostMessageRequest(
                        text = "Pong",
                        channel = slackCommand.channelId
                )).invoke()
    }
}

--

== Contributing

To contribute to the project, please read the https://github.com/kreait/slack-spring-boot-starter/blob/master/CONTRIBUTING.adoc[Contribution Guidelines]
