= First Event Receiver

:excerpt: This short guide will show you how to set up a Event receiver
:title: First Event Receiver
:order: 5
:source-highlighter: highlightjs

To write your first event receiver you need to write a component that implements the link:https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/receiver/EventReceiver.kt[EventReceiver] interface, you can use the  link:client/slack-api-client/src/main/kotlin/io/olaph/slack/client/SlackClient.kt[SlackClient] that is automatically registered with the starter

Example EventReceiver which sends a message when a channel is renamed (channel_rename permission required)



This Receiver overrides the `supportsEvent()`-method to ensure that it is only invoked when the correct event is received.
The https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/broker/EventBroker.kt[EventReceiver] takes care of receiving the event and forwards it to the right Receiver.
In this example, we receive the channel_rename event and send a message to the renamed channel.
To receive the event, you have to subscribe to channel_rename in the https://api.slack.com/apps[Slack App Console]

[source,kotlin]
--
include::../samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/ChannelRenamedEventReceiver.kt[lines=12..-1]]
--
