= First Interactive Component Receiver

:excerpt: This short guide will show you how to set up a Interactive Component receiver
:title: First Interactive Component Receiver
:order: 4

To write your first command receiver you write a component that implements the link:starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/receiver/InteractiveComponentReceiver.kt[InteractiveComponentReceiver] interface you can use the  link:client/slack-api-client/src/main/kotlin/io/olaph/slack/client/SlackClient.kt[SlackClient] that is automatically registered with the starter



This Receiver overrides the `supportsInteractiveMessage(`-method to ensure that it is only invoked when the correct component is received

the https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/broker/InteractiveComponentBroker.kt[InteractiveComponentBroker] takes care of receiving the component and forwards it to the right Receiver.
In this example, we created a complete dialog flow, by setting up and invoking the /open-dialog command, we

[source,kotlin]
--
include::../samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/DialogWorkflow.kt[lines=18..-1]]
--
