[[credentials]]
= Credentials Provider


== SystemPropertyCredentialsProvider

to set your credentials as System Properties, enter the following properties to your start command:

```
-Dslack.application.cliend-id=<YOUR CLIENT ID>
-Dslack.application.cliend-secret=<YOUR CLIENT SECRET>
-Dslack.application.signing-secret=<YOUR SIGNING SECRET>
```

== EnvironmentVariableCredentialsProvider

to set your credentials as Environment Variables, set the following variables:

```
SLACK_APP_CLIENT_ID=<YOUR CLIENT ID>
SLACK_APP_CLIENT_SECRET=<YOUR CLIENT SECRET>
SLACK_APP_SIGNING_SECRET=<YOUR SIGNING SECRET>
```

== CredentialsFileCredentialsProvider

to set your credentials persisted in your .slack directory create a credentials-file (simply a file called 'credentials' without extension) with the following content:

```
slack_app_client_id=<YOUR CLIENT ID>
slack_app_client_secret=<YOUR CLIENT SECRET>
slack_app_signing_secret=<YOUR SIGNING SECRET>
```

== Default Setup (InMemoryTeamStore)

The Installation basically works by implementing the SDK.
By Default an https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/store/InMemoryTeamStore.kt[InMemoryTeamStore] is auto configured.
The InMemoryTeamStore saves the Team that installed the App into a Map(*which is cleared after restarting the Application*)

== File Team Store

Since the In Memory TeamStore is cleared as soon as the service stops, we implemented the https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/store/FileTeamStore.kt[FileTeamStore] to persist the installations.
To use the FileTeamStore, add the following line to your application.properties slack.store.type=file On the next start, the SDK will create an team-store.json file under your .slack directory if it doesn't exist yet.
Now install your app by clicking on your link:installation_button[Install-Button] and the Team is stored in this json file.

== upcoming

We are planning to implement a MongoTeamStore to ease your way out to production