[[credentials]]
= Credentials Provider

The credentials provider is used to allow easy configuration of the slack app credentials in a local environment and the actual hosted service

== SystemPropertyCredentialsProvider

to set your credentials as System Properties, enter the following properties to your start command:

```
-Dslack.application.cliend-id=<YOUR CLIENT ID>
-Dslack.application.cliend-secret=<YOUR CLIENT SECRET>
-Dslack.application.signing-secret=<YOUR SIGNING SECRET>
```

== EnvironmentVariableCredentialsProvider

to set your credentials as Environment Variables, set the following variables:

```
SLACK_APP_CLIENT_ID=<YOUR CLIENT ID>
SLACK_APP_CLIENT_SECRET=<YOUR CLIENT SECRET>
SLACK_APP_SIGNING_SECRET=<YOUR SIGNING SECRET>
```

== CredentialsFileCredentialsProvider

To set your credentials persisted in your .slack directory create a credentials-file (simply a file called 'credentials' without extension) with the following content:
This is the recommended way to store your credentials for local development
```
slack_app_client_id=<YOUR CLIENT ID>
slack_app_client_secret=<YOUR CLIENT SECRET>
slack_app_signing_secret=<YOUR SIGNING SECRET>
```

== CredentialsProviderChain
The CredentialsProviderChain allows to chain multiple CredentialProviders which will try to resolve your credentials. This is useful in a situations
like having local credentials in a *credentials file* for development and *environment variables* in the hosted environment

