[[kotlin-sample-extensions]]
= Kotlin Sample Extensions
:google-analytics-account: UA-82654714-4

This guide will guide you through the process of building your own Slash Command Receiver class with Slack Spring Boot Starter.
We will use the extension package which extends all DTOs with .sample() methods, which will come in handy for testing.

[NOTE]
====
Slack Spring Boot Starter is not optimized for java
====

=== What you will need

- An IDE of your choice - preferably IntelliJ IDEA
- at least JDK 1.8
- Gradle 5

=== Preparation

First you'll need to have a build.gradle file

To use the test-extensions, simply include the following in your build.gradle:

[source,subs="attributes"]
--
testImplementation(group: "com.kreait.slack", name: "slack-jackson-dto-test", version: "{lib-version}")


--

Additionally we want to have have

[source,subs="attributes"]
--
testImplementation(group: "com.kreait.slack", name: "slack-spring-test-api-client", version: "{lib-version}")
--

in our build.gradle in order to test the functionality of our example.

=== The Slash Command Receiver

The https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/receiver/SlashCommandReceiver.kt[Slash Command Receiver] is an interface that is based around handling Slash Commands.

Let's assume we have the following class that implements the https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/receiver/SlashCommandReceiver.kt[Slash Command Receiver]:

[source,kotlin]
--
include::../../../../../../samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/ResponseCommandReceiver.kt[]
--

This class uses the https://github.com/kreait/slack-spring-boot-starter/blob/master/client/slack-api-client/src/main/kotlin/com/kreait/slack/api/SlackClient.kt[SlackClient] and a https://github.com/kreait/slack-spring-boot-starter/blob/master/samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/ResponseHandler.kt[ResponseHandler] to interact with slack and to react on the response from slack.

The https://github.com/kreait/slack-spring-boot-starter/blob/master/client/slack-api-client/src/main/kotlin/com/kreait/slack/api/SlackClient.kt[SlackClient] interface basically is the specification for handling Slack API interactions based on the Slack API design.
The https://github.com/kreait/slack-spring-boot-starter/blob/master/samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/ResponseHandler.kt[ResponseHandler] is used to tell if the execution of the command either was successful or unsuccessful.

The key methods are the supportsCommand and onReceiverSlashCommand.
The ```supportsCommand``` Method returns true if the command provided matches the expression.

The method ```onReceiveCommand``` will only be invoked if ```supportsCommand``` returns true.

The methods declared in the SlackClient extend their respective method groups which ultimately inherit the https://github.com/kreait/slack-spring-boot-starter/blob/master/client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/ApiCallMethod.kt[ApiCallMethod] providing the methods ```with```, ```onSuccess``` and ```onFailure``` that are used in the ```onReceiveCommand``` method.
We use them to provide the payload used in the ```message()``` call and to determine if the API call was successful or if it failed.

Now with this being set we want to test if our application is working as expected by utilizing tests.

=== Testing our class

First create a test class with a descriptive name.
In this class we want to verify if the invocation of the command was successfully executed and if there is a reaction if the invocation fails.

We create a method named ```testSuccess``` (or however you want to call it) and annotate it with ```@Test``` and give it a proper display name with the ```@DisplayName("...")``` annotation.

First we declare a new ```MockSlackClient``` which inherits the ```SlackClient``` and overrides it's methods with Mock-Methods which respectively inherit the original https://github.com/kreait/slack-spring-boot-starter/blob/master/client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/respond/MockRespondMethodGroup.kt[MethodGroup].
The mock-method group (in our case MockRespondMethodGroup) inherits the original method-group and overrides the methods with mock-methods.

In this example we override ```fun message()``` and return a ```MockRespondMessage``` object.

The MockRespondMethod inherits https://github.com/kreait/slack-spring-boot-starter/blob/master/client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/respond/RespondMessageMethod.kt[RespondMessageMethod] and the https://github.com/kreait/slack-spring-boot-starter/blob/master/client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/MockMethod.kt[MockMethod] and utilizes their methods.

This is how the first method will look like:

[source,kotlin]
--
include::../../../../../../samples/slack-spring-boot-starter-sample/src/test/kotlin/com/kreait/slack/sample/ResponseCommandReceiverTest.kt[lines=17..34]
--

Our ```mockSlackClient``` invokes the .respond().message() methods with a payload ("www.test.com") and sets the successResponse value to ```Unit``` since we don't return anything upon successfully posting a response.
By setting ```successResponse``` we also state that the invocation is treated as "successful".

We then mock the https://github.com/kreait/slack-spring-boot-starter/blob/master/samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/ResponseHandler.kt[ResponseHandler] so we can post a message in Slack with the status of the invocation in either the ```.onSuccess``` or ```.onFailure``` block.

The declaration of the ResponseCommandReceiver is provided with our mockSlackClient and the responseHandler so the actual test can be done.

We call the ```onReceiveSlashCommand``` from our just declared commandReceiver and provide it with the neccessary parameters.
The first parameter is a sample of a SlackCommand - but here it is completely empty.
In combination with the copy-Method we get a duplicate of this sample but can pick the parameters we like to alternate without having to fill in every parameter again.
In this example we change the ```command```, the ```channelId``` and the ```responseUrl```.
Additionally we need to provide HttpHeaders and a Token.

In this case HTTPHeaders are Empty and the Token is received by the Team in the https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/store/team/TeamStore.kt[TeamStore] we provided.

[NOTE]
====
The TeamStore is used to persist teams after the installation of a Slack App (either file or inMemory) since you'd have to reinstall the app after every start which in fact would be annoying.
The starter configures the InMemoryStore on default.
====

As our test method is used to verify a success, we first call the receiver:

[source,kotlin]
--
include::../../../../../../samples/slack-spring-boot-starter-sample/src/test/kotlin/com/kreait/slack/sample/ResponseCommandReceiverTest.kt[lines=28..30]
--

After calling the ```onReceiveSlashCommand``` method we want to verify if the right ```ResponseHandler``` method was at least invoked once.

[NOTE]
====
Remember that the methods provided by the ResponseHandler are used in the .onSuccess or .onFailure blocks so we want to verify *their* usage and not the usage of the actual onReceiveSlashCommand method.
====

We verify that the successResponse-method is invoked once and the failureResponse-method is invoked zero times

[source,kotlin]
--
include::../../../../../../samples/slack-spring-boot-starter-sample/src/test/kotlin/com/kreait/slack/sample/ResponseCommandReceiverTest.kt[lines=32..33]
--

Now that we have successful invocation we also want to test the case where it fails.

For that we can just copy the method that we just created, rename it and set the ```failureResponse``` and switch the verify-statements.

[source,kotlin]
--
include::../../../../../../samples/slack-spring-boot-starter-sample/src/test/kotlin/com/kreait/slack/sample/ResponseCommandReceiverTest.kt[lines=42]
--

[source,kotlin]
--
include::../../../../../../samples/slack-spring-boot-starter-sample/src/test/kotlin/com/kreait/slack/sample/ResponseCommandReceiverTest.kt[lines=51..52]
--

==== Summary

After completing this guide you gained the power to create your own Slash Command Class including it's tests.
Congratulations!
:-)

==== See also:

https://github.com/kreait/slack-spring-boot-starter/blob/master/docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/credentials.adoc[Credentials] +
https://github.com/kreait/slack-spring-boot-starter/blob/master/docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/mock-client.adoc[MockClient] +
https://github.com/kreait/slack-spring-boot-starter/blob/master/docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/teamstore.adoc[TeamStore]
