== Team Store

The TeamStore is an abstraction that will store teams that install the slack app. The store is used to resolve and provide team information to implementations
of InteractiveComponentReceiver, SlashCommandReceiver, EventReceiver and MismatchCommandReceiver

== InMemoryTeamStore.footnote:[This implementation exists to allow fast prototyping and is not recommended for production environments]
https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/store/InMemoryTeamStore.kt[InMemoryTeamStore] is the simplest
implementation and saves teams into the memory. (*which is cleared after restarting the Application*)


== FileTeamStore.footnote:[This implementation exists to allow local development and is not recommended for production environments]

Since the InMemoryTeamStore is cleared as soon as the service stops, we implemented the https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/store/FileTeamStore.kt[FileTeamStore] to persist the installations.
To use the FileTeamStore, add the following line to your application.properties slack.store.type=file On the next start, the SDK will create an team-store.json file under your .slack directory if it doesn't exist yet.
Now install your app by clicking on your link:installation_button[Install-Button] and the Team is stored in this json file.

== Upcoming
At the moment you need to implement your own team store if you want a to persist your teams
But we are planning to provide implementations for MongoDB and JPA
